# Generated by Django 5.0 on 2025-06-24 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatebox',
            options={'ordering': ('-last_message',)},
        ),
        migrations.AddField(
            model_name='privatebox',
            name='last_message',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
