# Generated by Django 5.0 on 2025-06-24 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_module', '0003_privatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 24, 12, 0, 7, 677517, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
