# Generated by Django 5.0 on 2025-06-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_module', '0005_privatemessage_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pv_files/'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
