# Generated by Django 5.0 on 2025-06-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_module', '0006_alter_privatemessage_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatemessage',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
