# Generated by Django 5.0 on 2025-06-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupbox',
            options={'ordering': ('-last_message',)},
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
