# Generated by Django 5.0 on 2025-06-28 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_module', '0002_alter_groupbox_options_alter_groupmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='gp_files/'),
        ),
        migrations.CreateModel(
            name='GroupAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='gp_avatars/')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_avatars', to='group_module.groupbox')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
