# Generated by Django 5.0 on 2025-06-28 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_module', '0003_alter_groupmessage_file_groupavatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupbox',
            name='admin',
        ),
        migrations.AddField(
            model_name='groupbox',
            name='admin',
            field=models.ManyToManyField(related_name='admins_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
