# Generated by Django 5.0 on 2025-06-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_module', '0004_remove_groupbox_admin_groupbox_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupbox',
            old_name='admin',
            new_name='admins',
        ),
    ]
