# Generated by Django 5.0 on 2025-06-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_module', '0005_rename_admin_groupbox_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupavatar',
            name='is_delete',
        ),
    ]
