# Generated by Django 5.0 on 2025-06-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_module', '0006_remove_groupavatar_is_delete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupAvatar',
            new_name='GroupBoxAvatar',
        ),
    ]
