# Generated by Django 5.0 on 2025-06-28 19:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_module', '0007_rename_groupavatar_groupboxavatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupMessage',
            new_name='GroupBoxMessage',
        ),
    ]
