# Generated by Django 5.0 on 2025-07-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_module', '0008_rename_groupmessage_groupboxmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupboxavatar',
            name='avatar',
            field=models.ImageField(upload_to='gp_avatars/'),
        ),
    ]
