# Generated by Django 5.0 on 2025-07-08 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_module', '0009_alter_groupboxavatar_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupboxmessage',
            name='group',
        ),
        migrations.AddField(
            model_name='groupboxmessage',
            name='box',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='box', to='group_module.groupbox'),
            preserve_default=False,
        ),
    ]
