# Generated by Django 5.0 on 2025-06-27 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
